### ISSUE TITLE
Grenades crashing server when chunk is loaded

### ISSUE THREAD

**Issue by victorbetoni** [nexusnode/crafting-dead#114] opened 2021-05-24 01:16 UTC
Apparently the problem is in this line: [Line](https://github.com/nexusnode/crafting-dead/blob/c35f8257f1ded065d0edbd7ed4a6c2311ed78e0f/crafting-dead-core/src/main/java/com/craftingdead/core/world/entity/grenade/GrenadeEntity.java#L232)

for some reason the grenade still activated even after the chunk is unloaded, and tries to be activated again when the chunk loads, resulting in a server crash.

**Comment by josephtarbit** [comment] 2021-05-25 19:57
Why do you think the problem is on that line?

**Comment by victorbetoni** [comment] 2021-05-25 23:06
I didn't express myself very well, but basically: The grenade that was crashing my server was specifically the flashbang, bc when the flashbang's entity is loaded and it still activated, it calls the FlashGrenadeEntity#flash() method, and this method tries to get the entities around the flashbang to flash them, but it's too early to do it, resulting in a crash. I didn't get any stacktrace in the console, just a crash report which mentioned this line: `at com.craftingdead.core.entity.grenade.FlashGrenadeEntity.flash(FlashGrenadeEntity.java:90)`

Btw, I applied  a workaround with mixins in this line, passing false to setActivated() every time. Worked well

**Comment by josephtarbit** [comment] 2021-05-29 18:26
Fixed in next update.

**Closed as completed by josephtarbit** 2021-05-29 18:26 UTC
