### ISSUE TITLE
Crash using other mods

### ISSUE THREAD

**Issue by GekidoLukas** [nexusnode/crafting-dead#130] opened 2021-06-23 13:33 UTC
Crash Report: https://pastebin.com/nqMiw2Gw
Crafting Dead Version: 1.16.5-1.6.1-alpha

What happened:
First, I updated the mod to the latest Version (Last working Version is 1.16.5-1.6.0_h1-alpha). Then I started the game and everything was as usual, but when I tried to start the world, it crashed.

I hope this crash report might help you to resolve this issue ^^

**Comment by josephtarbit** [comment] 2021-06-23 21:36
Duplicate of #127

**Closed as completed by josephtarbit** 2021-06-23 21:36 UTC
