### ISSUE TITLE
report

### ISSUE THREAD

**Issue by wkurumi** [nexusnode/crafting-dead#88] opened 2021-03-01 16:23 UTC
Mod monsters, no longer actively attack the player, version 1.3.0.

**Comment by Arownicc** [comment] 2021-03-01 16:56
there isn’t a v1.3.0 for this repository yet?

**Comment by wkurumi** [comment] 2021-03-01 17:06
> there isn’t a v1.3.0 for this repository yet?
actions

**Comment by josephtarbit** [comment] 2021-03-02 20:15
Closing as can't reproduce.

**Closed as completed by josephtarbit** 2021-03-02 20:15 UTC
