### ISSUE TITLE
[Issue] Armor not work.

### ISSUE THREAD

**Issue by SmileYik** [nexusnode/crafting-dead#112] opened 2021-05-07 02:40 UTC
Hello author.
In my test, I found that the weapon made damage on a player which put on armor as same as a player which have not armor.
And for all of guns can one shoot to kill a player if hit his head.

Minecraft: 1.16.5
CraftingDead: 1.28-1.41.

**Comment by josephtarbit** [comment] 2021-05-23 19:03
Which armour are you referring to?

**Comment by SmileYik** [comment] 2021-05-24 00:11
all.

**Comment by josephtarbit** [comment] 2021-06-13 22:08
Closing as can't reproduce.

**Closed as completed by josephtarbit** 2021-06-13 22:08 UTC
